# Generated by Django 5.1.2 on 2024-10-31 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Group',
                'verbose_name_plural': 'Data Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('xpath', models.CharField(max_length=500)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean')], max_length=50)),
                ('previously_verified_data', models.TextField(blank=True, null=True)),
                ('current_verified_data', models.TextField(blank=True, null=True)),
                ('current_unverified_data', models.TextField(blank=True, null=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('AUTO', 'Automated'), ('MANUAL', 'Manual'), ('VERIFY', 'Verification Required'), ('FIX', 'Fix Needed')], default='AUTO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datapoints', to='datapointScraperApp.datagroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='datapointScraperApp.organization')),
            ],
            options={
                'verbose_name': 'Datapoint',
                'verbose_name_plural': 'Datapoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datagroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datagroups', to='datapointScraperApp.organization'),
        ),
    ]
