# Generated by Django 5.1.2 on 2024-11-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapointScraperApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datagroup',
            options={'permissions': [('can_scrape_datagroup', 'Can scrape a specific DataGroup')], 'verbose_name': 'DataGroup', 'verbose_name_plural': 'DataGroups'},
        ),
        migrations.AlterModelOptions(
            name='datapoint',
            options={'ordering': ['-created_at'], 'permissions': [('can_scrape_datapoint', 'Can scrape a specific Datapoint'), ('can_scrape_all_datapoints', 'Can scrape all Datapoints')], 'verbose_name': 'Datapoint', 'verbose_name_plural': 'Datapoints'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('can_scrape_organisation', 'Can scrape all Datapoints/Datagroups in an Organization')], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
    ]
